name: Executar Script Diariamente

permissions:
  contents: write

on:
  schedule:
    - cron: '0 09 * * *'  # Executa diariamente às 6h (UTC-3)
    - cron: '0 15 * * *'  # Executa diariamente às 17h (UTC-3) -> 20h UTC
    - cron: '0 22 * * *'  # Executa diariamente às 24h (UTC-3) -> 20h UTC
  workflow_dispatch:  # Permite execução manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SENHA_API: ${{ secrets.SENHA_API }}

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use a versão desejada

      - name: Instalar dependências
        run: |
          pip install requests paramiko pandas pytz Flask openpyxl psutil  # Adicione todas as dependências necessárias

      - name: Executar o marchon
        run: python marchon.py  # Substitua pelo nome do seu arquivo

      - name: Executar Marchon10
        run: python marchon10.py
